version: '3'
services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: YourStrong@Passw0rd

    ports:
      - "5434:1433"
    networks:
      - mynetwork

  fitnessapp:
    image: ${DOCKER_REGISTRY-}fitnessapp
    build:
      context: .
      dockerfile: FitnessApp/Dockerfile
    depends_on:
      - sqldata
    networks:
      - mynetwork

networks:
  mynetwork:
